# Generated by Django 2.2.11 on 2021-02-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logo',
            new_name='Logos',
        ),
    ]
