# Generated by Django 2.2.11 on 2021-02-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210203_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logos',
            new_name='Logo',
        ),
    ]
